In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Salary_Data.csv')
dataset

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
X

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [4]:
Y

array([ 39343.,  46205.,  37731.,  43525.,  39891.,  56642.,  60150.,
        54445.,  64445.,  57189.,  63218.,  55794.,  56957.,  57081.,
        61111.,  67938.,  66029.,  83088.,  81363.,  93940.,  91738.,
        98273., 101302., 113812., 109431., 105582., 116969., 112635.,
       122391., 121872.])

In [8]:
Y = Y.reshape(len(Y),1)
Y

array([[ 39343.],
       [ 46205.],
       [ 37731.],
       [ 43525.],
       [ 39891.],
       [ 56642.],
       [ 60150.],
       [ 54445.],
       [ 64445.],
       [ 57189.],
       [ 63218.],
       [ 55794.],
       [ 56957.],
       [ 57081.],
       [ 61111.],
       [ 67938.],
       [ 66029.],
       [ 83088.],
       [ 81363.],
       [ 93940.],
       [ 91738.],
       [ 98273.],
       [101302.],
       [113812.],
       [109431.],
       [105582.],
       [116969.],
       [112635.],
       [122391.],
       [121872.]])

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
sc_y = StandardScaler()
x_train = sc_x.fit_transform(x_train)
y_train = sc_y.fit_transform(y_train)
x_train

array([[ 1.75832984],
       [-0.40973925],
       [ 0.09356251],
       [ 1.10016601],
       [-0.83560996],
       [ 0.01613147],
       [-0.7194634 ],
       [-0.21616165],
       [ 1.21631257],
       [ 0.6742953 ],
       [-1.45505827],
       [ 2.10676952],
       [-0.79689444],
       [-1.1066186 ],
       [ 0.32585562],
       [ 0.36457114],
       [-0.52588581],
       [-0.7194634 ],
       [ 1.52603672],
       [-1.18404964],
       [-1.53248931],
       [ 0.79044186],
       [-0.06129957],
       [-0.40973925]])

In [20]:
from sklearn.svm import SVR
regressor = SVR(kernel = 'rbf')
regressor.fit(x_train, y_train)

C:\Users\hp\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [21]:
y_train

array([[ 1.56283548],
       [-0.72970392],
       [ 0.37113122],
       [ 1.1057473 ],
       [-0.69550196],
       [-0.31690082],
       [-0.3807875 ],
       [-0.51525604],
       [ 1.61030683],
       [ 0.72000731],
       [-1.11645222],
       [ 1.93538674],
       [-0.55401557],
       [-1.3711116 ],
       [ 0.30155767],
       [ 0.80881947],
       [-0.67344009],
       [-0.78411245],
       [ 1.27837039],
       [-1.22454331],
       [-1.39321381],
       [ 0.98358017],
       [-0.23990609],
       [-0.68279723]])

In [38]:
y_pred = sc_y.inverse_transform(regressor.predict(sc_x.transform(x_test)).reshape(-1,1))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1))))

[[1.40e+00]
 [1.84e-01]
 [2.04e-01]
 [2.27e-01]
 [1.84e-01]
 [1.84e-01]
 [3.77e+04]
 [1.22e+05]
 [5.71e+04]
 [6.32e+04]
 [1.17e+05]
 [1.09e+05]]


In [39]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-6.582679665073902